// Re-export all constants
export * from "./sidebar";
export * from "./dashboard";
export * from "./announcements";
export * from "./documents";
export * from "./gallery";
export * from "./calendar";
export * from "./teachers";
export * from "./resolutions";
export * from "./agreements";
export * from "./links";
export * from "./publications";
export * from "./accreditation";
export * from "./routes";
export * from "./posgrado";
