export const ROUTE_NAMES: Record<string, string> = {
  admin: "Dashboard",
  announcements: "Anuncios",
  documents: "Documentos",
  gallery: "Galería",
  content: "Contenido",
  hero: "Hero",
  research: "Investigación",
  offices: "Oficinas",
  authorities: "Autoridades",
  calendar: "Calendario",
  footer: "Footer",
  teachers: "Docentes",
  "teachers-renacyt": "Docentes RENACYT",
  "research-groups": "Grupos de Investigación",
  semilleros: "Semilleros",
  publications: "Publicaciones",
  resolutions: "Resoluciones",
  decanales: "Decanales",
  rectorales: "Rectorales",
  agreements: "Convenios",
  links: "Enlaces",
  accreditation: "Acreditación",
  etica: "Ética",
  posgrado: "Posgrado",
  new: "Nuevo",
};
